# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SongPetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('performers', models.CharField(max_length=50)),
                ('table', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
